- name: Install neovim
  community.general.pacman:
    name: neovim
    state: latest
  become: yes
  become_method: doas
- name: Install node for coc
  community.general.pacman:
    name: 
      - nodejs
      - npm
    state: latest
  become: true
  become_method: doas
- name: Install vim plug
  shell: curl -fLo "{{ansible_env.HOME}}/.local/share"/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
- name: Install vim plug packages
  shell: | 
    nvim +PlugInstall +qall --headless
    nvim +CocInstall +qall --headless
