- name: Install kde plasma
  community.general.pacman:
    name: 
      - plasma
      - dolphin
      - kate
      - konsole
    state: latest
  become: yes
  become_method: doas
- shell: mkdir /etc/sddm.conf.d/
  become: yes
  become_method: doas
- name: Set sddm theme
  shell: echo -e "[Theme]\nCurrent=breeze" > /etc/sddm.conf.d/theme.conf
  become: yes
  become_method: doas
- name: Enable and start sddm
  service:
    name: sddm
    enabled: yes
    state: started
  become: yes
  become_method: doas
- name: Create .config dir
  file:
    path: "{{ansible_env.HOME}}/.config"
    state: directory
- name: Enable kde dark theme
  shell: echo -e "[KDE]\nLookAndFeelPackage=org.kde.breezedark.desktop" > {{ansible_env.HOME}}/.config/kdeglobals
 
